# Generated by Django 5.2.4 on 2025-07-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/users/%Y/%m/%d/', verbose_name='Photo'),
        ),
    ]
