# Generated by Django 5.2.4 on 2025-07-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('likes', models.IntegerField(default=0)),
                ('about', models.TextField(blank=True)),
                ('post', models.TextField(blank=True)),
            ],
        ),
    ]
