# Generated by Django 5.2.4 on 2025-07-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homee', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='static/photos/%Y/%m/%d', verbose_name='Image'),
        ),
    ]
