# Generated by Django 5.2.4 on 2025-07-14 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homee', '0002_home_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
