# Generated by Django 5.2.4 on 2025-07-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homee', '0003_alter_home_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='is_published',
            field=models.BooleanField(default=1),
        ),
    ]
