# Generated by Django 5.2.4 on 2025-07-23 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homee', '0004_remove_home_likes_home_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagPost2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Tag2',
                'verbose_name_plural': 'Tags2',
            },
        ),
        migrations.AddField(
            model_name='home',
            name='tags2',
            field=models.ManyToManyField(blank=True, related_name='posts2', to='homee.tagpost2'),
        ),
    ]
