# Generated by Django 5.2.4 on 2025-07-23 08:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homee', '0005_tagpost2_home_tags2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='home',
            options={'ordering': ['-time_update'], 'verbose_name': 'Content'},
        ),
        migrations.RemoveIndex(
            model_name='home',
            name='homee_home_time_dbf39d_idx',
        ),
        migrations.AddIndex(
            model_name='home',
            index=models.Index(fields=['-time_update'], name='homee_home_time_up_df6037_idx'),
        ),
    ]
