# Generated by Django 5.2.4 on 2025-07-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homee', '0005_alter_home_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='is_published',
            field=models.BooleanField(choices=[(0, 'Drafts'), (1, 'Published')], default=0),
        ),
    ]
