# Generated by Django 5.2.4 on 2025-07-14 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homee', '0007_categories_home_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='homee.categories'),
        ),
    ]
