# Generated by Django 5.2.4 on 2025-07-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homee', '0008_alter_home_cat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='home',
            options={'ordering': ['-time']},
        ),
        migrations.AddIndex(
            model_name='home',
            index=models.Index(fields=['-time'], name='homee_home_time_dbf39d_idx'),
        ),
    ]
