# Generated by Django 5.2.4 on 2025-07-15 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homee', '0009_alter_home_options_home_homee_home_time_dbf39d_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='home',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='homee.tagpost'),
        ),
    ]
