# Generated by Django 5.2.4 on 2025-07-17 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homee', '0010_tagpost_home_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='upload_model')),
            ],
        ),
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='home',
            options={'ordering': ['-time'], 'verbose_name': 'Content'},
        ),
        migrations.AlterModelOptions(
            name='tagpost',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterField(
            model_name='home',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='homee.categories'),
        ),
        migrations.AlterField(
            model_name='home',
            name='content',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
