# Generated by Django 5.2.4 on 2025-07-18 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homee', '0011_uploadfiles_alter_categories_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d', verbose_name='Image'),
        ),
    ]
